// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MUButton: typeof import('./src/components/common/MUButton.vue')['default']
    MUCoin: typeof import('./src/components/common/MUCoin.vue')['default']
    MUFooter: typeof import('./src/components/site/MUFooter.vue')['default']
    MUIconButton: typeof import('./src/components/common/MUIconButton.vue')['default']
    MUNavbar: typeof import('./src/components/site/MUNavbar.vue')['default']
    MUSiteDynamicBackground: typeof import('./src/components/site/MUSiteDynamicBackground.vue')['default']
    MUSiteProfile: typeof import('./src/components/site/MUSiteProfile.vue')['default']
    MUTag: typeof import('./src/components/common/MUTag.vue')['default']
    MUTitle: typeof import('./src/components/typography/MUTitle.vue')['default']
    MUWalletAddr: typeof import('./src/components/common/MUWalletAddr.vue')['default']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
